name: Keep Backend Alive
on:
  schedule:
    - cron: "*/14 * * * *" # Chạy 14 phút 1 lần
  workflow_dispatch: # Cho phép chạy thủ công để test

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Healthcheck API
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" https://nextgen-cinema-be-1.onrender.com/api/public/health)
          echo "Status: $status_code"
          if [ $status_code -eq 200 ]; then
            echo "Backend is alive!"
          else
            echo "Backend returned error: $status_code"
            exit 1
          fi
